import Foundation
import NetworkExtension

@objc(ObstacleBridgeTunnelControl)
final class ObstacleBridgeTunnelControl: NSObject {
    private static let providerBundleIdentifier = "com.obstaclebridge.obstacle-bridge-ios.IPServer"
    private static let legacyLocalizedDescription = "ObstacleBridge"
    private static let legacyLocalizedDescriptionAlt = "AdminWeb"
    private static let providerConfigurationBaseVersion = "2026-05-17-ios-config-derived-tunnel-v1"
    // Generated by scripts/write_build_info.py on every iOS build refresh.
    private static let providerBuildTimestampUTC = "2026-05-30T08:02:32Z"
    private static var providerConfigurationVersion: String {
        "\(providerConfigurationBaseVersion)+\(providerBuildTimestampUTC)"
    }
    private static let webAdminBind = "0.0.0.0"
    private static let webAdminPort = 18080
    private static let queue = DispatchQueue(label: "com.obstaclebridge.tunnel-control", qos: .utility)
    private static let statusDefaultsKey = "ObstacleBridgeTunnelControlStatus"
    private static let appGroupIdentifier = "group.com.obstaclebridge.shared"
    private static let defaultTunnelAddress = "192.168.106.1"
    private static let defaultTunnelPrefix = 30
    private static let defaultIncludedRoutes = ["0.0.0.0/0"]
    private static let defaultExcludedRoutes = ["127.0.0.0/8"]
    private static let defaultTunnelAddress6 = "fd20:106::1"
    private static let defaultTunnelPrefix6 = 126
    private static let defaultIncludedRoutes6 = ["::/0"]
    private static let defaultExcludedRoutes6 = ["::1/128"]
    private static let defaultDNS = ["1.1.1.1"]
    private static let defaultMTU = 1600
    private static let defaultIOSIfname = "ios-utun"
    private static var activeManager: NETunnelProviderManager?

    private struct DerivedTunnelNetworkSettings {
        let tunnelAddress: String
        let tunnelPrefix: Int
        let includedRoutes: [String]
        let excludedRoutes: [String]
        let tunnelAddress6: String
        let tunnelPrefix6: Int
        let includedRoutes6: [String]
        let excludedRoutes6: [String]
        let dnsServers: [String]
        let mtu: Int

        var providerConfiguration: [String: Any] {
            var payload: [String: Any] = [
                "schema": "obstaclebridge.ios.packet-tunnel.v1",
                "configuration_version": ObstacleBridgeTunnelControl.providerConfigurationVersion,
                "network_settings": [
                    "tunnel_address": tunnelAddress,
                    "tunnel_prefix": tunnelPrefix,
                    "included_routes": includedRoutes,
                    "excluded_routes": excludedRoutes,
                    "tunnel_address6": tunnelAddress6,
                    "tunnel_prefix6": tunnelPrefix6,
                    "included_routes6": includedRoutes6,
                    "excluded_routes6": excludedRoutes6,
                    "dns_servers": dnsServers,
                    "mtu": mtu,
                ],
            ]
            let runtimeConfig = ObstacleBridgeTunnelControl.loadRuntimeConfigJSON()
            if !runtimeConfig.isEmpty {
                payload["runtime_config"] = runtimeConfig
            }
            return payload
        }
    }

    @objc class func startIPServerTunnel() -> NSString {
        recordEvent("start_requested")
        queue.async {
            configureTunnel(startAfterInstall: true)
        }
        return jsonString([
            "ok": true,
            "requested": true,
            "provider_bundle_identifier": providerBundleIdentifier,
        ]) as NSString
    }

    @objc class func prepareIPServerTunnel() -> NSString {
        recordEvent("prepare_requested")
        queue.async {
            configureTunnel(startAfterInstall: false)
        }
        return jsonString([
            "ok": true,
            "requested": true,
            "provider_bundle_identifier": providerBundleIdentifier,
            "mode": "prepare_only",
        ]) as NSString
    }

    @objc class func harvestSharedLogs() -> NSString {
        var payload = harvestSharedLogsInternal()
        payload["config_sync"] = syncConfigurationFileInternal()
        return jsonString(payload) as NSString
    }

    @objc class func status() -> NSString {
        refreshStatusAsync()
        if let cached = UserDefaults.standard.dictionary(forKey: statusDefaultsKey) {
            return jsonString(cached) as NSString
        }
        return jsonString([
            "ok": true,
            "provider_bundle_identifier": providerBundleIdentifier,
            "installed": false,
            "enabled": false,
            "status": "unknown",
            "status_raw": -1,
            "cached": false,
        ]) as NSString
    }

    private class func configureTunnel(startAfterInstall: Bool) {
        let configSync = syncConfigurationFileInternal()
        recordEvent("config_sync_before_prepare", payload: configSync)
        NETunnelProviderManager.loadAllFromPreferences { managers, error in
            if let error {
                updateStatus(ok: false, event: "load_preferences_failed", error: error.localizedDescription)
                return
            }
            let allManagers = managers ?? []

            let selection = selectCanonicalManager(from: allManagers)
            let managersToRemove = selection.duplicates

            if !managersToRemove.isEmpty {
                removeDuplicateManagers(managersToRemove) {
                    queue.asyncAfter(deadline: .now() + 1.0) {
                        configureTunnel(startAfterInstall: startAfterInstall)
                    }
                }
                return
            }

            activeManager = selection.manager
            if selection.needsSave {

                configure(selection.manager)
                saveReloadAndMaybeStart(
                    selection.manager,
                    created: selection.created,
                    startAfterInstall: startAfterInstall
                )
            } else {
                updateStatus(
                    ok: true,
                    event: startAfterInstall ? "preferences_reused" : "preferences_prepared_reused",
                    manager: selection.manager,
                    extra: ["duplicates_removed": selection.duplicates.count]
                )
                restoreProtocolIdentityIfNeeded(selection.manager)
                if startAfterInstall {
                    start(selection.manager)
                    queue.asyncAfter(deadline: .now() + 3.0) {
                        updateStatus(ok: true, event: "post_start_status", manager: selection.manager)
                        updateStatus(
                            ok: true,
                            event: "provider_snapshot_deferred",
                            manager: selection.manager,
                            extra: ["context": "post_start_reused", "reason": "avoid_startup_provider_message_race"]
                        )
                    }
                } else {
                    updateStatus(
                        ok: true,
                        event: "profile_prepared",
                        manager: selection.manager,
                        extra: ["started": false]
                    )
                }
            }
        }
    }

    private class func selectCanonicalManager(
        from managers: [NETunnelProviderManager]
    ) -> (manager: NETunnelProviderManager, duplicates: [NETunnelProviderManager], needsSave: Bool, created: Bool) {
        recordEvent(
            "manager_inventory_scanned",
            payload: ["managers": managers.enumerated().map { managerInventory(index: $0.offset, manager: $0.element) }]
        )
        let related = managers.filter(isObstacleBridgeManager)
        let desiredManagers = related.filter { hasCurrentProviderConfiguration($0) }
            .sorted { a, b in
                let aScore = canonicalScore(for: a)
                let bScore = canonicalScore(for: b)
                return aScore > bScore
            }

        if let canonical = desiredManagers.first {
            let duplicates = related.filter { $0 !== canonical }
            let needsConfigurationRepair = !hasCurrentProviderConfiguration(canonical)
                || !hasCurrentProviderIdentifier(canonical)
                || !hasCurrentTunnelAddress(canonical)
                || canonical.localizedDescription != desiredLocalizedDescription()
            return (
                manager: canonical,
                duplicates: duplicates,
                needsSave: !canonical.isEnabled || needsConfigurationRepair,
                created: false
            )
        }

        if !related.isEmpty {
            let canonical = related.sorted { canonicalScore(for: $0) > canonicalScore(for: $1) }.first!
            let duplicates = related.filter { $0 !== canonical }
            return (
                manager: canonical,
                duplicates: duplicates,
                needsSave: true,
                created: false
            )
        }

        return (
            manager: NETunnelProviderManager(),
            duplicates: [],
            needsSave: true,
            created: true
        )
    }

    private class func isObstacleBridgeManager(_ manager: NETunnelProviderManager) -> Bool {
        hasCurrentProviderIdentifier(manager)
            || hasCurrentProviderConfiguration(manager)
            || hasCurrentTunnelAddress(manager)
            || hasCurrentProviderSchema(manager)
            || isLegacyObstacleBridgeManager(manager)
    }
    
    private class func isLegacyObstacleBridgeManager(_ manager: NETunnelProviderManager) -> Bool {
        if hasCurrentProviderIdentifier(manager) {
            return manager.localizedDescription != desiredLocalizedDescription()
        }

        return manager.localizedDescription == legacyLocalizedDescription
            || manager.localizedDescription == legacyLocalizedDescriptionAlt
            || manager.localizedDescription?.contains("ObstacleBridge") == true
    }


    private class func hasCurrentProviderIdentifier(_ manager: NETunnelProviderManager) -> Bool {
        (manager.protocolConfiguration as? NETunnelProviderProtocol)?.providerBundleIdentifier == providerBundleIdentifier
    }

    private class func hasCurrentProviderConfiguration(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol else {
            return false
        }
        guard let config = tunnelProtocol.providerConfiguration else {
            return false
        }
        let derived = deriveTunnelNetworkSettings()
        let desiredProviderConfiguration = derived.providerConfiguration as NSDictionary
        let currentProviderConfiguration = config as NSDictionary
        return currentProviderConfiguration == desiredProviderConfiguration
    }

    private class func hasCurrentTunnelAddress(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol else {
            return false
        }
        return tunnelProtocol.serverAddress == deriveTunnelNetworkSettings().tunnelAddress
    }

    private class func hasCurrentProviderSchema(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol else {
            return false
        }
        return (tunnelProtocol.providerConfiguration?["schema"] as? String) == "obstaclebridge.ios.packet-tunnel.v1"
    }

    private class func canonicalScore(for manager: NETunnelProviderManager) -> Int {
        var score = 0
        if hasCurrentProviderConfiguration(manager) {
            score += 8
        }
        if hasCurrentProviderIdentifier(manager) {
            score += 4
        }
        if hasCurrentTunnelAddress(manager) {
            score += 2
        }
        if manager.isEnabled {
            score += 1
        }
        return score
    }

    private class func desiredLocalizedDescription() -> String {
        let filteredScalars = providerBuildTimestampUTC.unicodeScalars.filter {
            CharacterSet.alphanumerics.contains($0)
        }
        let sanitized = String(String.UnicodeScalarView(filteredScalars))
        return "build\(sanitized)"
    }

    private class func managerInventory(index: Int, manager: NETunnelProviderManager) -> [String: Any] {
        var payload: [String: Any] = [
            "index": index,
            "enabled": manager.isEnabled,
            "localized_description": manager.localizedDescription ?? "",
            "status": statusText(manager.connection.status),
            "status_raw": manager.connection.status.rawValue,
        ]
        if let protocolConfiguration = manager.protocolConfiguration as? NETunnelProviderProtocol {
            payload["protocol_type"] = "NETunnelProviderProtocol"
            payload["protocol_provider_bundle_identifier"] = protocolConfiguration.providerBundleIdentifier ?? ""
            payload["protocol_server_address"] = protocolConfiguration.serverAddress ?? ""
            payload["protocol_username"] = protocolConfiguration.username ?? ""
            payload["provider_configuration_version"] =
                protocolConfiguration.providerConfiguration?["configuration_version"] as? String ?? ""
            payload["provider_configuration_schema"] =
                protocolConfiguration.providerConfiguration?["schema"] as? String ?? ""
        } else if manager.protocolConfiguration != nil {
            payload["protocol_type"] = String(describing: type(of: manager.protocolConfiguration!))
        } else {
            payload["protocol_type"] = ""
        }
        return payload
    }

    private class func removeDuplicateManagers(
        _ managers: [NETunnelProviderManager],
        completion: @escaping () -> Void
    ) {
        guard !managers.isEmpty else {
            completion()
            return
        }

        updateStatus(
            ok: true,
            event: "duplicate_cleanup_requested",
            extra: ["duplicate_count": managers.count]
        )

        let group = DispatchGroup()

        for manager in managers {
            group.enter()
            manager.removeFromPreferences { error in
                defer { group.leave() }

                if let error {
                    updateStatus(
                        ok: false,
                        event: "duplicate_cleanup_failed",
                        manager: manager,
                        error: error.localizedDescription
                    )
                    return
                }

                updateStatus(ok: true, event: "duplicate_cleanup_removed", manager: manager)
            }
        }

        group.notify(queue: queue) {
            updateStatus(
                ok: true,
                event: "duplicate_cleanup_completed",
                extra: ["duplicate_count": managers.count]
            )
            completion()
        }
    }

    private class func saveReloadAndMaybeStart(
        _ manager: NETunnelProviderManager,
        created: Bool,
        startAfterInstall: Bool
    ) {
        updateStatus(ok: true, event: "pre_save_snapshot", manager: manager, extra: ["created": created])
        manager.saveToPreferences { error in
            if let error {
                updateStatus(ok: false, event: "save_preferences_failed", manager: manager, error: error.localizedDescription)
                return
            }
            updateStatus(ok: true, event: "preferences_saved", manager: manager, extra: ["created": created])

            reloadCanonicalManager(event: "preferences_reloaded") { reloadedManager in
                guard let reloadedManager else {
                    return
                }

                let repairedAfterReload = restoreProtocolIdentityIfNeeded(reloadedManager)
                updateStatus(
                    ok: true,
                    event: "preferences_reloaded_checked",
                    manager: reloadedManager,
                    extra: ["repaired_after_reload": repairedAfterReload]
                )

                if startAfterInstall {
                    start(reloadedManager)
                } else {
                    updateStatus(
                        ok: true,
                        event: "profile_prepared",
                        manager: reloadedManager,
                        extra: ["created": created, "started": false]
                    )
                }
            }
        }
    }

    private class func ensureTunnelProtocol(
        for manager: NETunnelProviderManager
    ) -> NETunnelProviderProtocol? {
        if let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol {
            return tunnelProtocol
        }
        let tunnelProtocol = NETunnelProviderProtocol()
        manager.protocolConfiguration = tunnelProtocol
        return manager.protocolConfiguration as? NETunnelProviderProtocol
    }

    private class func configure(_ manager: NETunnelProviderManager) {
        guard let tunnelProtocol = ensureTunnelProtocol(for: manager) else {
            updateStatus(ok: false, event: "configure_failed_missing_tunnel_protocol", manager: manager)
            return
        }
        applyIdentity(to: tunnelProtocol, manager: manager)
        manager.localizedDescription = desiredLocalizedDescription()
        manager.isEnabled = true
        updateStatus(
            ok: true,
            event: "configured",
            manager: manager,
            extra: [
                "configuration_version": providerConfigurationVersion,
                "provider_configuration_mode": "config_derived_profile_persistence",
                "tunnel_address": deriveTunnelNetworkSettings().tunnelAddress,
                "tunnel_prefix": deriveTunnelNetworkSettings().tunnelPrefix,
                "included_routes": deriveTunnelNetworkSettings().includedRoutes,
                "excluded_routes": deriveTunnelNetworkSettings().excludedRoutes,
                "tunnel_address6": deriveTunnelNetworkSettings().tunnelAddress6,
                "tunnel_prefix6": deriveTunnelNetworkSettings().tunnelPrefix6,
                "included_routes6": deriveTunnelNetworkSettings().includedRoutes6,
                "excluded_routes6": deriveTunnelNetworkSettings().excludedRoutes6,
            ]
        )
    }

    @discardableResult
    private class func restoreProtocolIdentityIfNeeded(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = ensureTunnelProtocol(for: manager) else {
            return false
        }
        let repaired = applyIdentity(to: tunnelProtocol, manager: manager)
        if repaired {
            updateStatus(ok: true, event: "protocol_identity_repaired", manager: manager)
        }
        return repaired
    }

    @discardableResult
    private class func applyIdentity(
        to tunnelProtocol: NETunnelProviderProtocol,
        manager: NETunnelProviderManager
    ) -> Bool {
        let derived = deriveTunnelNetworkSettings()
        var repaired = false
        if tunnelProtocol.providerBundleIdentifier != providerBundleIdentifier {
            tunnelProtocol.providerBundleIdentifier = providerBundleIdentifier
            repaired = true
        }
        if tunnelProtocol.serverAddress != derived.tunnelAddress {
            tunnelProtocol.serverAddress = derived.tunnelAddress
            repaired = true
        }
        if tunnelProtocol.username != nil && tunnelProtocol.username != "" {
            tunnelProtocol.username = nil
            repaired = true
        }
        let desiredLocalizedDescription = desiredLocalizedDescription()
        if manager.localizedDescription != desiredLocalizedDescription {
            manager.localizedDescription = desiredLocalizedDescription
            repaired = true
        }
        let desiredProviderConfiguration = derived.providerConfiguration as NSDictionary
        let currentProviderConfiguration = tunnelProtocol.providerConfiguration as NSDictionary?
        if currentProviderConfiguration != desiredProviderConfiguration {
            tunnelProtocol.providerConfiguration = derived.providerConfiguration
            repaired = true
        }
        return repaired
    }

    private class func deriveTunnelNetworkSettings() -> DerivedTunnelNetworkSettings {
        let payload = loadRuntimeConfigJSON()

        if let own = findLocalIOSTunnelService(payload: payload) {
            for env in hookEnvBlocks(service: own) {
                if let derived = derivedSettingsFromLocalEnv(env, mtu: mtuFrom(service: own, fallback: defaultMTU)) {
                    return applyNetworkOverride(payload: payload, base: derived)
                }
            }
        }

        if let remote = findRemoteTunnelServiceTargetingIOS(payload: payload) {
            for env in hookEnvBlocks(service: remote) {
                if let derived = derivedSettingsFromRemoteEnv(env, mtu: mtuFrom(service: remote, fallback: defaultMTU)) {
                    return applyNetworkOverride(payload: payload, base: derived)
                }
            }
        }

        return applyNetworkOverride(
            payload: payload,
            base: DerivedTunnelNetworkSettings(
            tunnelAddress: defaultTunnelAddress,
            tunnelPrefix: defaultTunnelPrefix,
            includedRoutes: defaultIncludedRoutes,
            excludedRoutes: defaultExcludedRoutes,
            tunnelAddress6: defaultTunnelAddress6,
            tunnelPrefix6: defaultTunnelPrefix6,
            includedRoutes6: [],
            excludedRoutes6: [],
            dnsServers: defaultDNS,
            mtu: defaultMTU
            )
        )
    }

    private class func applyNetworkOverride(
        payload: [String: Any],
        base: DerivedTunnelNetworkSettings
    ) -> DerivedTunnelNetworkSettings {
        guard let override = payload["TUN_routing"] as? [String: Any] else {
            return base
        }
        return DerivedTunnelNetworkSettings(
            tunnelAddress: (override["tunnel_address"] as? String).flatMap { $0.isEmpty ? nil : $0 } ?? base.tunnelAddress,
            tunnelPrefix: (override["tunnel_prefix"] as? NSNumber)?.intValue ?? base.tunnelPrefix,
            includedRoutes: override["included_routes"] as? [String] ?? base.includedRoutes,
            excludedRoutes: override["excluded_routes"] as? [String] ?? base.excludedRoutes,
            tunnelAddress6: (override["tunnel_address6"] as? String) ?? base.tunnelAddress6,
            tunnelPrefix6: (override["tunnel_prefix6"] as? NSNumber)?.intValue ?? base.tunnelPrefix6,
            includedRoutes6: override["included_routes6"] as? [String] ?? base.includedRoutes6,
            excludedRoutes6: override["excluded_routes6"] as? [String] ?? base.excludedRoutes6,
            dnsServers: override["dns_servers"] as? [String] ?? base.dnsServers,
            mtu: (override["mtu"] as? NSNumber)?.intValue ?? base.mtu
        )
    }

    private class func loadRuntimeConfigJSON() -> [String: Any] {
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return [:]
        }
        let configURL = documents
            .appendingPathComponent("config", isDirectory: true)
            .appendingPathComponent("ObstacleBridge.cfg", isDirectory: false)
        guard
            let data = try? Data(contentsOf: configURL),
            let payload = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else {
            return [:]
        }
        return payload
    }

    private class func serviceCatalog(payload: [String: Any], key: String) -> [[String: Any]] {
        if
            let channelMux = payload["channel_mux"] as? [String: Any],
            let nested = channelMux[key] as? [[String: Any]]
        {
            return nested
        }
        return payload[key] as? [[String: Any]] ?? []
    }

    private class func findLocalIOSTunnelService(payload: [String: Any]) -> [String: Any]? {
        let services = serviceCatalog(payload: payload, key: "own_servers")
        return services.first { service in
            guard
                let listen = service["listen"] as? [String: Any],
                let proto = listen["protocol"] as? String,
                proto == "tun"
            else {
                return false
            }
            return (listen["ifname"] as? String) == defaultIOSIfname
        } ?? services.first { service in
            guard
                let listen = service["listen"] as? [String: Any],
                let proto = listen["protocol"] as? String
            else {
                return false
            }
            return proto == "tun"
        }
    }

    private class func findRemoteTunnelServiceTargetingIOS(payload: [String: Any]) -> [String: Any]? {
        let services = serviceCatalog(payload: payload, key: "remote_servers")
        return services.first { service in
            guard
                let listen = service["listen"] as? [String: Any],
                let target = service["target"] as? [String: Any],
                let proto = listen["protocol"] as? String
            else {
                return false
            }
            return proto == "tun" && (target["ifname"] as? String) == defaultIOSIfname
        } ?? services.first { service in
            guard
                let listen = service["listen"] as? [String: Any],
                let proto = listen["protocol"] as? String
            else {
                return false
            }
            return proto == "tun"
        }
    }

    private class func hookEnvBlocks(service: [String: Any]) -> [[String: Any]] {
        guard
            let hooks = service["lifecycle_hooks"] as? [String: Any],
            let listener = hooks["listener"] as? [String: Any]
        else {
            return []
        }
        var out: [[String: Any]] = []
        for event in ["on_created", "on_channel_connected", "on_stopped"] {
            guard
                let command = listener[event] as? [String: Any],
                let env = command["env"] as? [String: Any]
            else {
                continue
            }
            out.append(env)
        }
        return out
    }

    private class func mtuFrom(service: [String: Any], fallback: Int) -> Int {
        if
            let listen = service["listen"] as? [String: Any],
            let mtu = listen["mtu"] as? NSNumber
        {
            return mtu.intValue
        }
        if
            let target = service["target"] as? [String: Any],
            let mtu = target["mtu"] as? NSNumber
        {
            return mtu.intValue
        }
        return fallback
    }

    private class func derivedSettingsFromLocalEnv(_ env: [String: Any], mtu: Int) -> DerivedTunnelNetworkSettings? {
        guard let tunAddr = env["TUN_ADDR"] as? String else {
            return nil
        }
        guard let (addr, prefix) = parseCIDR(tunAddr, maxPrefix: 32) else {
            return nil
        }
        let tunnelAddr6 = (env["TUN_ADDR6"] as? String).flatMap { parseCIDR($0, maxPrefix: 128) }
        return DerivedTunnelNetworkSettings(
            tunnelAddress: addr,
            tunnelPrefix: prefix,
            includedRoutes: defaultIncludedRoutes,
            excludedRoutes: defaultExcludedRoutes,
            tunnelAddress6: tunnelAddr6?.0 ?? defaultTunnelAddress6,
            tunnelPrefix6: tunnelAddr6?.1 ?? defaultTunnelPrefix6,
            includedRoutes6: tunnelAddr6 == nil ? [] : defaultIncludedRoutes6,
            excludedRoutes6: tunnelAddr6 == nil ? [] : defaultExcludedRoutes6,
            dnsServers: defaultDNS,
            mtu: mtu
        )
    }

    private class func derivedSettingsFromRemoteEnv(_ env: [String: Any], mtu: Int) -> DerivedTunnelNetworkSettings? {
        guard let peerAddr = env["PEER_ADDR"] as? String, !peerAddr.isEmpty else {
            return nil
        }
        let prefix = parseCIDR(env["TUN_ADDR"] as? String ?? "", maxPrefix: 32)?.1
            ?? parseCIDR(env["TUN_SUBNET"] as? String ?? "", maxPrefix: 32)?.1
            ?? defaultTunnelPrefix
        let peerAddr6 = env["PEER_ADDR6"] as? String ?? ""
        let prefix6 = parseCIDR(env["TUN_ADDR6"] as? String ?? "", maxPrefix: 128)?.1
            ?? parseCIDR(env["TUN_SUBNET6"] as? String ?? "", maxPrefix: 128)?.1
            ?? defaultTunnelPrefix6
        return DerivedTunnelNetworkSettings(
            tunnelAddress: peerAddr,
            tunnelPrefix: prefix,
            includedRoutes: defaultIncludedRoutes,
            excludedRoutes: defaultExcludedRoutes,
            tunnelAddress6: peerAddr6,
            tunnelPrefix6: prefix6,
            includedRoutes6: peerAddr6.isEmpty ? [] : defaultIncludedRoutes6,
            excludedRoutes6: peerAddr6.isEmpty ? [] : defaultExcludedRoutes6,
            dnsServers: defaultDNS,
            mtu: mtu
        )
    }

    private class func parseCIDR(_ text: String, maxPrefix: Int) -> (String, Int)? {
        let parts = text.split(separator: "/", maxSplits: 1).map(String.init)
        guard parts.count == 2, let prefix = Int(parts[1]), prefix >= 0, prefix <= maxPrefix else {
            return nil
        }
        return (parts[0], prefix)
    }

    private class func harvestSharedLogsInternal() -> [String: Any] {
        guard let appDocuments = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return ["ok": false, "error": "app documents directory unavailable"]
        }
        guard let sharedContainer = FileManager.default.containerURL(
            forSecurityApplicationGroupIdentifier: appGroupIdentifier
        ) else {
            return ["ok": false, "error": "shared app-group container unavailable"]
        }

        let destinationDirectory = appDocuments.appendingPathComponent("logs", isDirectory: true)
        let sourceDirectory = sharedContainer.appendingPathComponent("logs", isDirectory: true)
        let fm = FileManager.default
        try? fm.createDirectory(at: destinationDirectory, withIntermediateDirectories: true)
        try? fm.createDirectory(at: sourceDirectory, withIntermediateDirectories: true)

        let destinationPrefix = "vpn-"
        if let existing = try? fm.contentsOfDirectory(at: destinationDirectory, includingPropertiesForKeys: nil) {
            for url in existing where url.lastPathComponent.hasPrefix(destinationPrefix) {
                try? fm.removeItem(at: url)
            }
        }

        var copied: [String] = []
        var cleared: [String] = []
        var errors: [[String: String]] = []

        let files = (try? fm.contentsOfDirectory(
            at: sourceDirectory,
            includingPropertiesForKeys: [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey],
            options: [.skipsHiddenFiles]
        )) ?? []

        let sourceInventory: [[String: Any]] = files.map { url in
            let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey])
            return [
                "name": url.lastPathComponent,
                "path": url.path,
                "is_regular": values?.isRegularFile ?? false,
                "size": values?.fileSize ?? -1,
                "modified": values?.contentModificationDate.map { ISO8601DateFormatter().string(from: $0) } ?? "",
            ]
        }

        recordEvent(
            "shared_logs_source_inventory",
            payload: [
                "source_directory": sourceDirectory.path,
                "file_count": sourceInventory.count,
                "files": sourceInventory,
            ]
        )

        for sourceURL in files {
            let values = try? sourceURL.resourceValues(forKeys: [.isRegularFileKey])
            guard values?.isRegularFile == true else {
                continue
            }
            let destinationURL = destinationDirectory.appendingPathComponent(destinationPrefix + sourceURL.lastPathComponent)
            do {
                if fm.fileExists(atPath: destinationURL.path) {
                    try fm.removeItem(at: destinationURL)
                }
                try fm.copyItem(at: sourceURL, to: destinationURL)
                copied.append(destinationURL.lastPathComponent)
                try fm.removeItem(at: sourceURL)
                cleared.append(sourceURL.lastPathComponent)
            } catch {
                errors.append([
                    "file": sourceURL.lastPathComponent,
                    "error": error.localizedDescription,
                ])
            }
        }

        let payload: [String: Any] = [
            "ok": errors.isEmpty,
            "copied_files": copied,
            "cleared_files": cleared,
            "errors": errors,
            "source_directory": sourceDirectory.path,
            "destination_directory": destinationDirectory.path,
            "source_inventory": sourceInventory,
        ]

        recordEvent("shared_logs_harvested", payload: payload)
        return payload
    }

    private struct FileSnapshot {
        let exists: Bool
        let size: Int
        let modifiedAt: Date?
        let path: String

        var dictionary: [String: Any] {
            [
                "exists": exists,
                "size": size,
                "modified": modifiedAt.map { ISO8601DateFormatter().string(from: $0) } ?? "",
                "path": path,
            ]
        }
    }

    private class func syncConfigurationFileInternal() -> [String: Any] {
        guard let appDocuments = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return ["ok": false, "error": "app documents directory unavailable"]
        }
        guard let sharedContainer = FileManager.default.containerURL(
            forSecurityApplicationGroupIdentifier: appGroupIdentifier
        ) else {
            return ["ok": false, "error": "shared app-group container unavailable"]
        }

        let fm = FileManager.default
        let appConfigDirectory = appDocuments.appendingPathComponent("config", isDirectory: true)
        let sharedConfigDirectory = sharedContainer.appendingPathComponent("config", isDirectory: true)
        try? fm.createDirectory(at: appConfigDirectory, withIntermediateDirectories: true)
        try? fm.createDirectory(at: sharedConfigDirectory, withIntermediateDirectories: true)

        let appConfigURL = appConfigDirectory.appendingPathComponent("ObstacleBridge.cfg")
        let sharedConfigURL = sharedConfigDirectory.appendingPathComponent("ObstacleBridge.cfg")
        let appDocumentsHintURL = sharedConfigDirectory.appendingPathComponent("app-documents-root.json")

        let appSnapshot = fileSnapshot(at: appConfigURL)
        let sharedSnapshot = fileSnapshot(at: sharedConfigURL)
        let decision = syncDecision(appConfig: appSnapshot, sharedConfig: sharedSnapshot)

        var copiedToApp = false
        var copiedToShared = false
        var errors: [[String: String]] = []

        if decision.copyAppToShared {
            do {
                try replaceFile(at: sharedConfigURL, with: appConfigURL)
                copiedToShared = true
            } catch {
                errors.append(["target": "shared", "error": error.localizedDescription])
            }
        }

        if decision.copySharedToApp {
            do {
                try replaceFile(at: appConfigURL, with: sharedConfigURL)
                copiedToApp = true
            } catch {
                errors.append(["target": "app", "error": error.localizedDescription])
            }
        }

        let finalAppSnapshot = fileSnapshot(at: appConfigURL)
        let finalSharedSnapshot = fileSnapshot(at: sharedConfigURL)
        let hintPayload: [String: Any] = [
            "documents_root": appDocuments.path,
            "config_file": appConfigURL.path,
            "written_at": ISO8601DateFormatter().string(from: Date()),
        ]
        if JSONSerialization.isValidJSONObject(hintPayload),
           let hintData = try? JSONSerialization.data(withJSONObject: hintPayload, options: [.sortedKeys]) {
            try? hintData.write(to: appDocumentsHintURL, options: [.atomic])
        }
        let payload: [String: Any] = [
            "ok": errors.isEmpty,
            "decision": decision.name,
            "copied_to_app": copiedToApp,
            "copied_to_shared": copiedToShared,
            "app_config": finalAppSnapshot.dictionary,
            "shared_config": finalSharedSnapshot.dictionary,
            "app_documents_hint_file": appDocumentsHintURL.path,
            "app_path": appConfigURL.path,
            "shared_path": sharedConfigURL.path,
            "errors": errors,
        ]
        recordEvent("config_sync_completed", payload: payload)
        return payload
    }

    private class func syncDecision(
        appConfig: FileSnapshot,
        sharedConfig: FileSnapshot
    ) -> (name: String, copyAppToShared: Bool, copySharedToApp: Bool) {
        switch (appConfig.exists, sharedConfig.exists) {
        case (false, false):
            return ("none_present", false, false)
        case (true, false):
            return ("seed_shared_from_app", true, false)
        case (false, true):
            return ("seed_app_from_shared", false, true)
        case (true, true):
            let appModified = appConfig.modifiedAt ?? .distantPast
            let sharedModified = sharedConfig.modifiedAt ?? .distantPast
            if appModified > sharedModified {
                return ("app_newer", true, false)
            }
            if sharedModified > appModified {
                return ("shared_newer", false, true)
            }
            return ("already_in_sync", false, false)
        }
    }

    private class func fileSnapshot(at url: URL) -> FileSnapshot {
        let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey])
        let exists = values?.isRegularFile == true
        return FileSnapshot(
            exists: exists,
            size: exists ? (values?.fileSize ?? -1) : -1,
            modifiedAt: exists ? values?.contentModificationDate : nil,
            path: url.path
        )
    }

    private class func replaceFile(at destinationURL: URL, with sourceURL: URL) throws {
        let fm = FileManager.default
        if fm.fileExists(atPath: destinationURL.path) {
            try fm.removeItem(at: destinationURL)
        }
        try fm.copyItem(at: sourceURL, to: destinationURL)
    }

    private class func reloadCanonicalManager(
        event: String,
        completion: @escaping (NETunnelProviderManager?) -> Void
    ) {
        NETunnelProviderManager.loadAllFromPreferences { managers, error in
            if let error {
                updateStatus(ok: false, event: "\(event)_load_all_failed", error: error.localizedDescription)
                completion(nil)
                return
            }

            let selection = selectCanonicalManager(from: managers ?? [])
            activeManager = selection.manager
            updateStatus(
                ok: true,
                event: event,
                manager: selection.manager,
                extra: [
                    "manager_count": managers?.count ?? 0,
                    "duplicate_count": selection.duplicates.count,
                    "needs_save": selection.needsSave,
                    "created": selection.created,
                ]
            )
            completion(selection.manager)
        }
    }

    private class func start(_ manager: NETunnelProviderManager) {
        let status = manager.connection.status
        if status == .connected || status == .connecting || status == .reasserting {
            updateStatus(ok: true, event: "already_started", manager: manager, extra: ["started": true])
            return
        }

        do {
            try manager.connection.startVPNTunnel()
            updateStatus(ok: true, event: "start_succeeded", manager: manager, extra: ["started": true])
        } catch {
            updateStatus(ok: false, event: "start_failed", manager: manager, error: error.localizedDescription)
        }
    }

    private class func requestProviderSnapshot(_ manager: NETunnelProviderManager, context: String) {
        guard manager.connection.status == .connected else {
            updateStatus(
                ok: true,
                event: "provider_snapshot_skipped",
                manager: manager,
                extra: [
                    "context": context,
                    "reason": "not_connected",
                ]
            )
            return
        }
        guard let session = manager.connection as? NETunnelProviderSession else {
            updateStatus(
                ok: false,
                event: "provider_snapshot_unavailable",
                manager: manager,
                error: "VPN connection is not a NETunnelProviderSession",
                extra: ["context": context]
            )
            return
        }
        let request: [String: Any] = [
            "command": "snapshot",
            "context": context,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: request) else {
            updateStatus(
                ok: false,
                event: "provider_snapshot_encode_failed",
                manager: manager,
                error: "failed to encode provider snapshot request",
                extra: ["context": context]
            )
            return
        }

        do {
            try session.sendProviderMessage(data) { responseData in
                guard let responseData else {
                    updateStatus(
                        ok: false,
                        event: "provider_snapshot_empty",
                        manager: manager,
                        error: "provider returned no snapshot data",
                        extra: ["context": context]
                    )
                    return
                }
                let response = (try? JSONSerialization.jsonObject(with: responseData)) as? [String: Any]
                updateStatus(
                    ok: true,
                    event: "provider_snapshot_received",
                    manager: manager,
                    extra: [
                        "context": context,
                        "provider_response": response ?? ["raw_bytes": responseData.count],
                    ]
                )
                if let response, response["mode"] as? String == "python_probe" {
                    requestProviderMessage(manager, command: "native_python_probe", context: context)
                }
            }
        } catch {
            updateStatus(
                ok: false,
                event: "provider_snapshot_failed",
                manager: manager,
                error: error.localizedDescription,
                extra: ["context": context]
            )
        }
    }

    private class func requestProviderMessage(_ manager: NETunnelProviderManager, command: String, context: String) {
        guard let session = manager.connection as? NETunnelProviderSession else {
            updateStatus(
                ok: false,
                event: "provider_message_unavailable",
                manager: manager,
                error: "VPN connection is not a NETunnelProviderSession",
                extra: [
                    "command": command,
                    "context": context,
                ]
            )
            return
        }
        let request: [String: Any] = [
            "command": command,
            "context": context,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: request) else {
            updateStatus(
                ok: false,
                event: "provider_message_encode_failed",
                manager: manager,
                error: "failed to encode provider message",
                extra: [
                    "command": command,
                    "context": context,
                ]
            )
            return
        }
        do {
            try session.sendProviderMessage(data) { responseData in
                guard let responseData else {
                    updateStatus(
                        ok: false,
                        event: "provider_message_empty",
                        manager: manager,
                        error: "provider returned no message data",
                        extra: [
                            "command": command,
                            "context": context,
                        ]
                    )
                    return
                }
                let response = (try? JSONSerialization.jsonObject(with: responseData)) as? [String: Any]
                updateStatus(
                    ok: true,
                    event: "provider_message_received",
                    manager: manager,
                    extra: [
                        "command": command,
                        "context": context,
                        "provider_response": response ?? ["raw_bytes": responseData.count],
                    ]
                )
                if command == "native_python_probe", response?["ok"] as? Bool == true {
                    requestProviderMessage(
                        manager,
                        command: "probe_module:obstacle_bridge",
                        context: context
                    )
                } else if command == "probe_module:obstacle_bridge", response?["ok"] as? Bool == true {
                    requestProviderMessage(
                        manager,
                        command: "probe_module:obstacle_bridge.core",
                        context: context
                    )
                } else if command == "probe_module:obstacle_bridge.core", response?["ok"] as? Bool == true {
                    requestProviderMessage(
                        manager,
                        command: "probe_module:obstacle_bridge_ios.diagnostics",
                        context: context
                    )
                } else if command == "probe_module:obstacle_bridge_ios.diagnostics", response?["ok"] as? Bool == true {
                    requestProviderMessage(
                        manager,
                        command: "probe_module:obstacle_bridge_ios.app",
                        context: context
                    )
                } else if command == "probe_module:obstacle_bridge_ios.app", response?["ok"] as? Bool == true {
                    requestProviderMessage(
                        manager,
                        command: "probe_module:obstacle_bridge_ios.ipserver_extension",
                        context: context
                    )
                }
            }
        } catch {
            updateStatus(
                ok: false,
                event: "provider_message_failed",
                manager: manager,
                error: error.localizedDescription,
                extra: [
                    "command": command,
                    "context": context,
                ]
            )
        }
    }

    private class func refreshStatusAsync() {
        queue.async {
            NETunnelProviderManager.loadAllFromPreferences { managers, error in
                if let error {
                    updateStatus(ok: false, event: "status_load_failed", error: error.localizedDescription)
                    return
                }
                let manager = (managers ?? []).first(where: isObstacleBridgeManager)
                updateStatus(ok: true, event: "status_refreshed", manager: manager ?? activeManager)
            }
        }
    }

    private class func updateStatus(
        ok: Bool,
        event: String,
        manager: NETunnelProviderManager? = nil,
        error: String? = nil,
        extra: [String: Any] = [:]
    ) {
        var payload: [String: Any] = [
            "ok": ok,
            "event": event,
            "provider_bundle_identifier": providerBundleIdentifier,
            "installed": manager != nil,
            "enabled": manager?.isEnabled ?? false,
            "status": statusText(manager?.connection.status),
            "status_raw": manager?.connection.status.rawValue ?? -1,
            "cached": true,
            "timestamp": ISO8601DateFormatter().string(from: Date()),
        ]
        if let error {
            payload["error"] = error
        }
        if let manager {
            payload["localized_description"] = manager.localizedDescription ?? ""
            if let protocolConfiguration = manager.protocolConfiguration as? NETunnelProviderProtocol {
                payload["protocol_server_address"] = protocolConfiguration.serverAddress ?? ""
                payload["protocol_username"] = protocolConfiguration.username ?? ""
                payload["protocol_provider_bundle_identifier"] = protocolConfiguration.providerBundleIdentifier ?? ""
                payload["provider_configuration_version"] =
                    protocolConfiguration.providerConfiguration?["configuration_version"] as? String ?? ""
            }
        }
        for (key, value) in extra {
            payload[key] = value
        }
        UserDefaults.standard.set(payload, forKey: statusDefaultsKey)
        recordEvent(event, payload: payload)
    }

    private class func recordEvent(_ event: String, payload: [String: Any] = [:]) {
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return
        }
        let logDirectory = documents.appendingPathComponent("logs", isDirectory: true)
        try? FileManager.default.createDirectory(at: logDirectory, withIntermediateDirectories: true)
        let logURL = logDirectory.appendingPathComponent("ios-native-tunnel-control.jsonl")
        var line = payload
        line["native_event"] = event
        line["timestamp"] = ISO8601DateFormatter().string(from: Date())
        guard JSONSerialization.isValidJSONObject(line),
              let data = try? JSONSerialization.data(withJSONObject: line, options: [.sortedKeys]),
              let text = String(data: data, encoding: .utf8)
        else {
            return
        }
        if let handle = try? FileHandle(forWritingTo: logURL) {
            defer {
                try? handle.close()
            }
            handle.seekToEndOfFile()
            handle.write(Data((text + "\n").utf8))
            return
        }
        try? (text + "\n").write(to: logURL, atomically: true, encoding: .utf8)
    }

    private class func loadRuntimeConfiguration() -> [String: Any] {
        let defaults: [String: Any] = [
            "admin_web": true,
            "admin_web_bind": webAdminBind,
            "admin_web_port": webAdminPort,
            "admin_web_path": "/",
            "log": "DEBUG",
            "file_level": "DEBUG",
            "console_level": "INFO",
        ]
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return defaults
        }
        let configURL = documents.appendingPathComponent("config/ObstacleBridge.cfg")
        guard let data = try? Data(contentsOf: configURL),
              let object = try? JSONSerialization.jsonObject(with: data),
              let payload = object as? [String: Any]
        else {
            return defaults
        }
        var flattened = defaults
        for (key, value) in payload {
            if let section = value as? [String: Any] {
                for (sectionKey, sectionValue) in section {
                    flattened[sectionKey] = sectionValue
                }
            } else {
                flattened[key] = value
            }
        }
        return flattened
    }

    private class func ipserverRuntimeConfiguration() -> [String: Any] {
        var config = loadRuntimeConfiguration()
        config["admin_web"] = true
        config["admin_web_bind"] = webAdminBind
        config["admin_web_port"] = webAdminPort
        config["admin_web_path"] = "/"
        return config
    }

    private class func statusText(_ status: NEVPNStatus?) -> String {
        guard let status else {
            return "unknown"
        }
        switch status {
        case .invalid:
            return "invalid"
        case .disconnected:
            return "disconnected"
        case .connecting:
            return "connecting"
        case .connected:
            return "connected"
        case .reasserting:
            return "reasserting"
        case .disconnecting:
            return "disconnecting"
        @unknown default:
            return "unknown"
        }
    }

    private class func jsonString(_ payload: [String: Any]) -> String {
        guard JSONSerialization.isValidJSONObject(payload),
              let data = try? JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys]),
              let text = String(data: data, encoding: .utf8)
        else {
            return "{\"ok\":false,\"error\":\"failed to encode tunnel-control response\"}"
        }
        return text
    }
}
