import Foundation
import NetworkExtension

@objc(ObstacleBridgeTunnelControl)
final class ObstacleBridgeTunnelControl: NSObject {
    private static let providerBundleIdentifier = "com.obstaclebridge.obstacle-bridge-ios.IPServer"
    private static let legacyLocalizedDescription = "ObstacleBridge"
    private static let legacyLocalizedDescriptionAlt = "AdminWeb"
    private static let providerConfigurationBaseVersion = "2026-05-17-ios-config-derived-tunnel-v1"
    // Generated by scripts/write_build_info.py on every iOS build refresh.
    private static let providerBuildTimestampUTC = "2026-05-31T22:38:32Z"
    private static var providerConfigurationVersion: String {
        "\(providerConfigurationBaseVersion)+\(providerBuildTimestampUTC)"
    }
    private static let webAdminBind = "0.0.0.0"
    private static let webAdminPort = 18080
    private static let queue = DispatchQueue(label: "com.obstaclebridge.tunnel-control", qos: .utility)
    private static let statusDefaultsKey = "ObstacleBridgeTunnelControlStatus"
    private static let appGroupIdentifier = "group.com.obstaclebridge.shared"
    private static let defaultTunnelAddress = "192.168.106.1"
    private static let defaultTunnelPrefix = 30
    private static let defaultIncludedRoutes = ["0.0.0.0/0"]
    private static let defaultExcludedRoutes = ["127.0.0.0/8"]
    private static let defaultTunnelAddress6 = "fd20:106::1"
    private static let defaultTunnelPrefix6 = 126
    private static let defaultIncludedRoutes6 = ["::/0"]
    private static let defaultExcludedRoutes6 = ["::1/128"]
    private static let defaultDNS = ["1.1.1.1"]
    private static let defaultMTU = 1600
    private static let defaultIOSIfname = "ios-utun"
    private static var activeManager: NETunnelProviderManager?
    private static var adminWebProxy: ObstacleBridgeIOSAppAdminWebProxy?

    private struct DerivedTunnelNetworkSettings {
        let tunnelAddress: String
        let tunnelPrefix: Int
        let includedRoutes: [String]
        let excludedRoutes: [String]
        let tunnelAddress6: String
        let tunnelPrefix6: Int
        let includedRoutes6: [String]
        let excludedRoutes6: [String]
        let dnsServers: [String]
        let mtu: Int

        init(shared: ObstacleBridgeDerivedTunnelSettings) {
            self.tunnelAddress = shared.tunnelAddress
            self.tunnelPrefix = shared.tunnelPrefix
            self.includedRoutes = shared.includedRoutes
            self.excludedRoutes = shared.excludedRoutes
            self.tunnelAddress6 = shared.tunnelAddress6
            self.tunnelPrefix6 = shared.tunnelPrefix6
            self.includedRoutes6 = shared.includedRoutes6
            self.excludedRoutes6 = shared.excludedRoutes6
            self.dnsServers = shared.dnsServers
            self.mtu = shared.mtu
        }

        var providerConfiguration: [String: Any] {
            var payload: [String: Any] = [
                "schema": "obstaclebridge.ios.packet-tunnel.v1",
                "configuration_version": ObstacleBridgeTunnelControl.providerConfigurationVersion,
                "network_settings": [
                    "tunnel_address": tunnelAddress,
                    "tunnel_prefix": tunnelPrefix,
                    "included_routes": includedRoutes,
                    "excluded_routes": excludedRoutes,
                    "tunnel_address6": tunnelAddress6,
                    "tunnel_prefix6": tunnelPrefix6,
                    "included_routes6": includedRoutes6,
                    "excluded_routes6": excludedRoutes6,
                    "dns_servers": dnsServers,
                    "mtu": mtu,
                ],
            ]
            let runtimeConfig = ObstacleBridgeTunnelControl.loadRuntimeConfigJSON()
            if !runtimeConfig.isEmpty {
                payload["runtime_config"] = runtimeConfig
            }
            return payload
        }
    }

    @objc class func startIPServerTunnel() -> NSString {
        recordEvent("start_requested")
        queue.async {
            configureTunnel(startAfterInstall: true)
        }
        return jsonString([
            "ok": true,
            "requested": true,
            "provider_bundle_identifier": providerBundleIdentifier,
        ]) as NSString
    }

    @objc class func prepareIPServerTunnel() -> NSString {
        recordEvent("prepare_requested")
        queue.async {
            configureTunnel(startAfterInstall: false)
        }
        return jsonString([
            "ok": true,
            "requested": true,
            "provider_bundle_identifier": providerBundleIdentifier,
            "mode": "prepare_only",
        ]) as NSString
    }

    @objc class func harvestSharedLogs() -> NSString {
        var payload = harvestSharedLogsInternal()
        payload["config_sync"] = syncConfigurationFileInternal()
        return jsonString(payload) as NSString
    }

    @objc class func status() -> NSString {
        refreshStatusAsync()
        if let cached = UserDefaults.standard.dictionary(forKey: statusDefaultsKey) {
            return jsonString(cached) as NSString
        }
        return jsonString([
            "ok": true,
            "provider_bundle_identifier": providerBundleIdentifier,
            "installed": false,
            "enabled": false,
            "status": "unknown",
            "status_raw": -1,
            "cached": false,
        ]) as NSString
    }

    private class func configureTunnel(startAfterInstall: Bool) {
        let configSync = syncConfigurationFileInternal()
        recordEvent("config_sync_before_prepare", payload: configSync)
        NETunnelProviderManager.loadAllFromPreferences { managers, error in
            if let error {
                updateStatus(ok: false, event: "load_preferences_failed", error: error.localizedDescription)
                return
            }
            let allManagers = managers ?? []

            let selection = selectCanonicalManager(from: allManagers)
            let managersToRemove = selection.duplicates

            if !managersToRemove.isEmpty {
                removeDuplicateManagers(managersToRemove) {
                    queue.asyncAfter(deadline: .now() + 1.0) {
                        configureTunnel(startAfterInstall: startAfterInstall)
                    }
                }
                return
            }

            activeManager = selection.manager
            ensureAdminWebProxy(selection.manager)
            if selection.needsSave {

                configure(selection.manager)
                saveReloadAndMaybeStart(
                    selection.manager,
                    created: selection.created,
                    startAfterInstall: startAfterInstall
                )
            } else {
                updateStatus(
                    ok: true,
                    event: startAfterInstall ? "preferences_reused" : "preferences_prepared_reused",
                    manager: selection.manager,
                    extra: ["duplicates_removed": selection.duplicates.count]
                )
                restoreProtocolIdentityIfNeeded(selection.manager)
                if startAfterInstall {
                    start(selection.manager)
                    queue.asyncAfter(deadline: .now() + 3.0) {
                        updateStatus(ok: true, event: "post_start_status", manager: selection.manager)
                        updateStatus(
                            ok: true,
                            event: "provider_snapshot_deferred",
                            manager: selection.manager,
                            extra: ["context": "post_start_reused", "reason": "avoid_startup_provider_message_race"]
                        )
                    }
                } else {
                    updateStatus(
                        ok: true,
                        event: "profile_prepared",
                        manager: selection.manager,
                        extra: ["started": false]
                    )
                }
            }
        }
    }

    private class func selectCanonicalManager(
        from managers: [NETunnelProviderManager]
    ) -> (manager: NETunnelProviderManager, duplicates: [NETunnelProviderManager], needsSave: Bool, created: Bool) {
        recordEvent(
            "manager_inventory_scanned",
            payload: ["managers": managers.enumerated().map { managerInventory(index: $0.offset, manager: $0.element) }]
        )
        let related = managers.filter(isObstacleBridgeManager)
        let desiredManagers = related.filter { hasCurrentProviderConfiguration($0) }
            .sorted { a, b in
                let aScore = canonicalScore(for: a)
                let bScore = canonicalScore(for: b)
                return aScore > bScore
            }

        if let canonical = desiredManagers.first {
            let duplicates = related.filter { $0 !== canonical }
            let needsConfigurationRepair = !hasCurrentProviderConfiguration(canonical)
                || !hasCurrentProviderIdentifier(canonical)
                || !hasCurrentTunnelAddress(canonical)
                || canonical.localizedDescription != desiredLocalizedDescription()
            return (
                manager: canonical,
                duplicates: duplicates,
                needsSave: !canonical.isEnabled || needsConfigurationRepair,
                created: false
            )
        }

        if !related.isEmpty {
            let canonical = related.sorted { canonicalScore(for: $0) > canonicalScore(for: $1) }.first!
            let duplicates = related.filter { $0 !== canonical }
            return (
                manager: canonical,
                duplicates: duplicates,
                needsSave: true,
                created: false
            )
        }

        return (
            manager: NETunnelProviderManager(),
            duplicates: [],
            needsSave: true,
            created: true
        )
    }

    private class func isObstacleBridgeManager(_ manager: NETunnelProviderManager) -> Bool {
        hasCurrentProviderIdentifier(manager)
            || hasCurrentProviderConfiguration(manager)
            || hasCurrentTunnelAddress(manager)
            || hasCurrentProviderSchema(manager)
            || isLegacyObstacleBridgeManager(manager)
    }
    
    private class func isLegacyObstacleBridgeManager(_ manager: NETunnelProviderManager) -> Bool {
        if hasCurrentProviderIdentifier(manager) {
            return manager.localizedDescription != desiredLocalizedDescription()
        }

        return manager.localizedDescription == legacyLocalizedDescription
            || manager.localizedDescription == legacyLocalizedDescriptionAlt
            || manager.localizedDescription?.contains("ObstacleBridge") == true
    }


    private class func hasCurrentProviderIdentifier(_ manager: NETunnelProviderManager) -> Bool {
        (manager.protocolConfiguration as? NETunnelProviderProtocol)?.providerBundleIdentifier == providerBundleIdentifier
    }

    private class func hasCurrentProviderConfiguration(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol else {
            return false
        }
        guard let config = tunnelProtocol.providerConfiguration else {
            return false
        }
        let derived = deriveTunnelNetworkSettings()
        let desiredProviderConfiguration = derived.providerConfiguration as NSDictionary
        let currentProviderConfiguration = config as NSDictionary
        return currentProviderConfiguration == desiredProviderConfiguration
    }

    private class func hasCurrentTunnelAddress(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol else {
            return false
        }
        return tunnelProtocol.serverAddress == deriveTunnelNetworkSettings().tunnelAddress
    }

    private class func hasCurrentProviderSchema(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol else {
            return false
        }
        return (tunnelProtocol.providerConfiguration?["schema"] as? String) == "obstaclebridge.ios.packet-tunnel.v1"
    }

    private class func canonicalScore(for manager: NETunnelProviderManager) -> Int {
        var score = 0
        if hasCurrentProviderConfiguration(manager) {
            score += 8
        }
        if hasCurrentProviderIdentifier(manager) {
            score += 4
        }
        if hasCurrentTunnelAddress(manager) {
            score += 2
        }
        if manager.isEnabled {
            score += 1
        }
        return score
    }

    private class func desiredLocalizedDescription() -> String {
        let filteredScalars = providerBuildTimestampUTC.unicodeScalars.filter {
            CharacterSet.alphanumerics.contains($0)
        }
        let sanitized = String(String.UnicodeScalarView(filteredScalars))
        return "build\(sanitized)"
    }

    private class func managerInventory(index: Int, manager: NETunnelProviderManager) -> [String: Any] {
        var payload: [String: Any] = [
            "index": index,
            "enabled": manager.isEnabled,
            "localized_description": manager.localizedDescription ?? "",
            "status": statusText(manager.connection.status),
            "status_raw": manager.connection.status.rawValue,
        ]
        if let protocolConfiguration = manager.protocolConfiguration as? NETunnelProviderProtocol {
            payload["protocol_type"] = "NETunnelProviderProtocol"
            payload["protocol_provider_bundle_identifier"] = protocolConfiguration.providerBundleIdentifier ?? ""
            payload["protocol_server_address"] = protocolConfiguration.serverAddress ?? ""
            payload["protocol_username"] = protocolConfiguration.username ?? ""
            payload["provider_configuration_version"] =
                protocolConfiguration.providerConfiguration?["configuration_version"] as? String ?? ""
            payload["provider_configuration_schema"] =
                protocolConfiguration.providerConfiguration?["schema"] as? String ?? ""
        } else if manager.protocolConfiguration != nil {
            payload["protocol_type"] = String(describing: type(of: manager.protocolConfiguration!))
        } else {
            payload["protocol_type"] = ""
        }
        return payload
    }

    private class func removeDuplicateManagers(
        _ managers: [NETunnelProviderManager],
        completion: @escaping () -> Void
    ) {
        guard !managers.isEmpty else {
            completion()
            return
        }

        updateStatus(
            ok: true,
            event: "duplicate_cleanup_requested",
            extra: ["duplicate_count": managers.count]
        )

        let group = DispatchGroup()

        for manager in managers {
            group.enter()
            manager.removeFromPreferences { error in
                defer { group.leave() }

                if let error {
                    updateStatus(
                        ok: false,
                        event: "duplicate_cleanup_failed",
                        manager: manager,
                        error: error.localizedDescription
                    )
                    return
                }

                updateStatus(ok: true, event: "duplicate_cleanup_removed", manager: manager)
            }
        }

        group.notify(queue: queue) {
            updateStatus(
                ok: true,
                event: "duplicate_cleanup_completed",
                extra: ["duplicate_count": managers.count]
            )
            completion()
        }
    }

    private class func saveReloadAndMaybeStart(
        _ manager: NETunnelProviderManager,
        created: Bool,
        startAfterInstall: Bool
    ) {
        updateStatus(ok: true, event: "pre_save_snapshot", manager: manager, extra: ["created": created])
        manager.saveToPreferences { error in
            if let error {
                updateStatus(ok: false, event: "save_preferences_failed", manager: manager, error: error.localizedDescription)
                return
            }
            updateStatus(ok: true, event: "preferences_saved", manager: manager, extra: ["created": created])

            reloadCanonicalManager(event: "preferences_reloaded") { reloadedManager in
                guard let reloadedManager else {
                    return
                }

                let repairedAfterReload = restoreProtocolIdentityIfNeeded(reloadedManager)
                updateStatus(
                    ok: true,
                    event: "preferences_reloaded_checked",
                    manager: reloadedManager,
                    extra: ["repaired_after_reload": repairedAfterReload]
                )

                if startAfterInstall {
                    start(reloadedManager)
                } else {
                    updateStatus(
                        ok: true,
                        event: "profile_prepared",
                        manager: reloadedManager,
                        extra: ["created": created, "started": false]
                    )
                }
            }
        }
    }

    private class func ensureTunnelProtocol(
        for manager: NETunnelProviderManager
    ) -> NETunnelProviderProtocol? {
        if let tunnelProtocol = manager.protocolConfiguration as? NETunnelProviderProtocol {
            return tunnelProtocol
        }
        let tunnelProtocol = NETunnelProviderProtocol()
        manager.protocolConfiguration = tunnelProtocol
        return manager.protocolConfiguration as? NETunnelProviderProtocol
    }

    private class func configure(_ manager: NETunnelProviderManager) {
        guard let tunnelProtocol = ensureTunnelProtocol(for: manager) else {
            updateStatus(ok: false, event: "configure_failed_missing_tunnel_protocol", manager: manager)
            return
        }
        applyIdentity(to: tunnelProtocol, manager: manager)
        manager.localizedDescription = desiredLocalizedDescription()
        manager.isEnabled = true
        updateStatus(
            ok: true,
            event: "configured",
            manager: manager,
            extra: [
                "configuration_version": providerConfigurationVersion,
                "provider_configuration_mode": "config_derived_profile_persistence",
                "tunnel_address": deriveTunnelNetworkSettings().tunnelAddress,
                "tunnel_prefix": deriveTunnelNetworkSettings().tunnelPrefix,
                "included_routes": deriveTunnelNetworkSettings().includedRoutes,
                "excluded_routes": deriveTunnelNetworkSettings().excludedRoutes,
                "tunnel_address6": deriveTunnelNetworkSettings().tunnelAddress6,
                "tunnel_prefix6": deriveTunnelNetworkSettings().tunnelPrefix6,
                "included_routes6": deriveTunnelNetworkSettings().includedRoutes6,
                "excluded_routes6": deriveTunnelNetworkSettings().excludedRoutes6,
            ]
        )
    }

    @discardableResult
    private class func restoreProtocolIdentityIfNeeded(_ manager: NETunnelProviderManager) -> Bool {
        guard let tunnelProtocol = ensureTunnelProtocol(for: manager) else {
            return false
        }
        let repaired = applyIdentity(to: tunnelProtocol, manager: manager)
        if repaired {
            updateStatus(ok: true, event: "protocol_identity_repaired", manager: manager)
        }
        return repaired
    }

    @discardableResult
    private class func applyIdentity(
        to tunnelProtocol: NETunnelProviderProtocol,
        manager: NETunnelProviderManager
    ) -> Bool {
        let derived = deriveTunnelNetworkSettings()
        var repaired = false
        if tunnelProtocol.providerBundleIdentifier != providerBundleIdentifier {
            tunnelProtocol.providerBundleIdentifier = providerBundleIdentifier
            repaired = true
        }
        if tunnelProtocol.serverAddress != derived.tunnelAddress {
            tunnelProtocol.serverAddress = derived.tunnelAddress
            repaired = true
        }
        if tunnelProtocol.username != nil && tunnelProtocol.username != "" {
            tunnelProtocol.username = nil
            repaired = true
        }
        let desiredLocalizedDescription = desiredLocalizedDescription()
        if manager.localizedDescription != desiredLocalizedDescription {
            manager.localizedDescription = desiredLocalizedDescription
            repaired = true
        }
        let desiredProviderConfiguration = derived.providerConfiguration as NSDictionary
        let currentProviderConfiguration = tunnelProtocol.providerConfiguration as NSDictionary?
        if currentProviderConfiguration != desiredProviderConfiguration {
            tunnelProtocol.providerConfiguration = derived.providerConfiguration
            repaired = true
        }
        return repaired
    }

    private class func deriveTunnelNetworkSettings() -> DerivedTunnelNetworkSettings {
        let payload = loadRuntimeConfigJSON()

        if let own = findLocalIOSTunnelService(payload: payload),
           let derived = own.derivedLocalTunnelSettings(
            defaultTunnelAddress6: defaultTunnelAddress6,
            defaultTunnelPrefix6: defaultTunnelPrefix6,
            defaultIncludedRoutes: defaultIncludedRoutes,
            defaultExcludedRoutes: defaultExcludedRoutes,
            defaultIncludedRoutes6: defaultIncludedRoutes6,
            defaultExcludedRoutes6: defaultExcludedRoutes6,
            defaultDNS: defaultDNS,
            fallbackMTU: defaultMTU
           ) {
            let overridden = ObstacleBridgeRuntimeConfig.tunnelRoutingOverride(from: payload).map { derived.applying($0) } ?? derived
            return DerivedTunnelNetworkSettings(shared: overridden)
        }

        if let remote = findRemoteTunnelServiceTargetingIOS(payload: payload),
           let derived = remote.derivedRemoteTunnelSettings(
            defaultTunnelPrefix: defaultTunnelPrefix,
            defaultTunnelPrefix6: defaultTunnelPrefix6,
            defaultIncludedRoutes: defaultIncludedRoutes,
            defaultExcludedRoutes: defaultExcludedRoutes,
            defaultIncludedRoutes6: defaultIncludedRoutes6,
            defaultExcludedRoutes6: defaultExcludedRoutes6,
            defaultDNS: defaultDNS,
            fallbackMTU: defaultMTU
           ) {
            let overridden = ObstacleBridgeRuntimeConfig.tunnelRoutingOverride(from: payload).map { derived.applying($0) } ?? derived
            return DerivedTunnelNetworkSettings(shared: overridden)
        }

        let base = ObstacleBridgeDerivedTunnelSettings(
            tunnelAddress: defaultTunnelAddress,
            tunnelPrefix: defaultTunnelPrefix,
            includedRoutes: defaultIncludedRoutes,
            excludedRoutes: defaultExcludedRoutes,
            tunnelAddress6: defaultTunnelAddress6,
            tunnelPrefix6: defaultTunnelPrefix6,
            includedRoutes6: [],
            excludedRoutes6: [],
            dnsServers: defaultDNS,
            mtu: defaultMTU
        )
        let overridden = ObstacleBridgeRuntimeConfig.tunnelRoutingOverride(from: payload).map { base.applying($0) } ?? base
        return DerivedTunnelNetworkSettings(shared: overridden)
    }

    private class func loadRuntimeConfigJSON() -> [String: Any] {
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return [:]
        }
        let configURL = documents
            .appendingPathComponent("config", isDirectory: true)
            .appendingPathComponent("ObstacleBridge.cfg", isDirectory: false)
        guard
            let data = try? Data(contentsOf: configURL),
            let payload = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else {
            return [:]
        }
        return payload
    }

    private class func findLocalIOSTunnelService(payload: [String: Any]) -> ObstacleBridgeRuntimeServiceSpec? {
        let services = ObstacleBridgeRuntimeConfig.ownServerSpecs(from: payload, preserveInputIndices: true)
        return services.first { service in
            service.listenProtocol == "tun" && service.listenIfname == defaultIOSIfname
        } ?? services.first { service in
            service.listenProtocol == "tun"
        }
    }

    private class func findRemoteTunnelServiceTargetingIOS(payload: [String: Any]) -> ObstacleBridgeRuntimeServiceSpec? {
        let services = ObstacleBridgeRuntimeConfig.remoteServerSpecs(from: payload, preserveInputIndices: true)
        return services.first { service in
            service.listenProtocol == "tun" && service.targetIfname == defaultIOSIfname
        } ?? services.first { service in
            service.listenProtocol == "tun"
        }
    }

    private class func harvestSharedLogsInternal() -> [String: Any] {
        guard let appDocuments = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return ["ok": false, "error": "app documents directory unavailable"]
        }
        guard let sharedContainer = FileManager.default.containerURL(
            forSecurityApplicationGroupIdentifier: appGroupIdentifier
        ) else {
            return ["ok": false, "error": "shared app-group container unavailable"]
        }

        let destinationDirectory = appDocuments.appendingPathComponent("logs", isDirectory: true)
        let sourceDirectory = sharedContainer.appendingPathComponent("logs", isDirectory: true)
        let fm = FileManager.default
        try? fm.createDirectory(at: destinationDirectory, withIntermediateDirectories: true)
        try? fm.createDirectory(at: sourceDirectory, withIntermediateDirectories: true)

        let destinationPrefix = "vpn-"
        if let existing = try? fm.contentsOfDirectory(at: destinationDirectory, includingPropertiesForKeys: nil) {
            for url in existing where url.lastPathComponent.hasPrefix(destinationPrefix) {
                try? fm.removeItem(at: url)
            }
        }

        var copied: [String] = []
        var cleared: [String] = []
        var errors: [[String: String]] = []

        let files = (try? fm.contentsOfDirectory(
            at: sourceDirectory,
            includingPropertiesForKeys: [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey],
            options: [.skipsHiddenFiles]
        )) ?? []

        let sourceInventory: [[String: Any]] = files.map { url in
            let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey])
            return [
                "name": url.lastPathComponent,
                "path": url.path,
                "is_regular": values?.isRegularFile ?? false,
                "size": values?.fileSize ?? -1,
                "modified": values?.contentModificationDate.map { ISO8601DateFormatter().string(from: $0) } ?? "",
            ]
        }

        recordEvent(
            "shared_logs_source_inventory",
            payload: [
                "source_directory": sourceDirectory.path,
                "file_count": sourceInventory.count,
                "files": sourceInventory,
            ]
        )

        for sourceURL in files {
            let values = try? sourceURL.resourceValues(forKeys: [.isRegularFileKey])
            guard values?.isRegularFile == true else {
                continue
            }
            let destinationURL = destinationDirectory.appendingPathComponent(destinationPrefix + sourceURL.lastPathComponent)
            do {
                if fm.fileExists(atPath: destinationURL.path) {
                    try fm.removeItem(at: destinationURL)
                }
                try fm.copyItem(at: sourceURL, to: destinationURL)
                copied.append(destinationURL.lastPathComponent)
                try fm.removeItem(at: sourceURL)
                cleared.append(sourceURL.lastPathComponent)
            } catch {
                errors.append([
                    "file": sourceURL.lastPathComponent,
                    "error": error.localizedDescription,
                ])
            }
        }

        let payload: [String: Any] = [
            "ok": errors.isEmpty,
            "copied_files": copied,
            "cleared_files": cleared,
            "errors": errors,
            "source_directory": sourceDirectory.path,
            "destination_directory": destinationDirectory.path,
            "source_inventory": sourceInventory,
        ]

        recordEvent("shared_logs_harvested", payload: payload)
        return payload
    }

    private struct FileSnapshot {
        let exists: Bool
        let size: Int
        let modifiedAt: Date?
        let path: String

        var dictionary: [String: Any] {
            [
                "exists": exists,
                "size": size,
                "modified": modifiedAt.map { ISO8601DateFormatter().string(from: $0) } ?? "",
                "path": path,
            ]
        }
    }

    private class func syncConfigurationFileInternal() -> [String: Any] {
        guard let appDocuments = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return ["ok": false, "error": "app documents directory unavailable"]
        }
        guard let sharedContainer = FileManager.default.containerURL(
            forSecurityApplicationGroupIdentifier: appGroupIdentifier
        ) else {
            return ["ok": false, "error": "shared app-group container unavailable"]
        }

        let fm = FileManager.default
        let appConfigDirectory = appDocuments.appendingPathComponent("config", isDirectory: true)
        let sharedConfigDirectory = sharedContainer.appendingPathComponent("config", isDirectory: true)
        try? fm.createDirectory(at: appConfigDirectory, withIntermediateDirectories: true)
        try? fm.createDirectory(at: sharedConfigDirectory, withIntermediateDirectories: true)

        let appConfigURL = appConfigDirectory.appendingPathComponent("ObstacleBridge.cfg")
        let sharedConfigURL = sharedConfigDirectory.appendingPathComponent("ObstacleBridge.cfg")
        let appDocumentsHintURL = sharedConfigDirectory.appendingPathComponent("app-documents-root.json")

        let appSnapshot = fileSnapshot(at: appConfigURL)
        let sharedSnapshot = fileSnapshot(at: sharedConfigURL)
        let decision = syncDecision(appConfig: appSnapshot, sharedConfig: sharedSnapshot)

        var copiedToApp = false
        var copiedToShared = false
        var errors: [[String: String]] = []

        if decision.copyAppToShared {
            do {
                try replaceFile(at: sharedConfigURL, with: appConfigURL)
                copiedToShared = true
            } catch {
                errors.append(["target": "shared", "error": error.localizedDescription])
            }
        }

        if decision.copySharedToApp {
            do {
                try replaceFile(at: appConfigURL, with: sharedConfigURL)
                copiedToApp = true
            } catch {
                errors.append(["target": "app", "error": error.localizedDescription])
            }
        }

        let finalAppSnapshot = fileSnapshot(at: appConfigURL)
        let finalSharedSnapshot = fileSnapshot(at: sharedConfigURL)
        let hintPayload: [String: Any] = [
            "documents_root": appDocuments.path,
            "config_file": appConfigURL.path,
            "written_at": ISO8601DateFormatter().string(from: Date()),
        ]
        if JSONSerialization.isValidJSONObject(hintPayload),
           let hintData = try? JSONSerialization.data(withJSONObject: hintPayload, options: [.sortedKeys]) {
            try? hintData.write(to: appDocumentsHintURL, options: [.atomic])
        }
        let payload: [String: Any] = [
            "ok": errors.isEmpty,
            "decision": decision.name,
            "copied_to_app": copiedToApp,
            "copied_to_shared": copiedToShared,
            "app_config": finalAppSnapshot.dictionary,
            "shared_config": finalSharedSnapshot.dictionary,
            "app_documents_hint_file": appDocumentsHintURL.path,
            "app_path": appConfigURL.path,
            "shared_path": sharedConfigURL.path,
            "errors": errors,
        ]
        recordEvent("config_sync_completed", payload: payload)
        return payload
    }

    private class func syncDecision(
        appConfig: FileSnapshot,
        sharedConfig: FileSnapshot
    ) -> (name: String, copyAppToShared: Bool, copySharedToApp: Bool) {
        switch (appConfig.exists, sharedConfig.exists) {
        case (false, false):
            return ("none_present", false, false)
        case (true, false):
            return ("seed_shared_from_app", true, false)
        case (false, true):
            return ("seed_app_from_shared", false, true)
        case (true, true):
            let appModified = appConfig.modifiedAt ?? .distantPast
            let sharedModified = sharedConfig.modifiedAt ?? .distantPast
            if appModified > sharedModified {
                return ("app_newer", true, false)
            }
            if sharedModified > appModified {
                return ("shared_newer", false, true)
            }
            return ("already_in_sync", false, false)
        }
    }

    private class func fileSnapshot(at url: URL) -> FileSnapshot {
        let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey])
        let exists = values?.isRegularFile == true
        return FileSnapshot(
            exists: exists,
            size: exists ? (values?.fileSize ?? -1) : -1,
            modifiedAt: exists ? values?.contentModificationDate : nil,
            path: url.path
        )
    }

    private class func replaceFile(at destinationURL: URL, with sourceURL: URL) throws {
        let fm = FileManager.default
        if fm.fileExists(atPath: destinationURL.path) {
            try fm.removeItem(at: destinationURL)
        }
        try fm.copyItem(at: sourceURL, to: destinationURL)
    }

    private class func reloadCanonicalManager(
        event: String,
        completion: @escaping (NETunnelProviderManager?) -> Void
    ) {
        NETunnelProviderManager.loadAllFromPreferences { managers, error in
            if let error {
                updateStatus(ok: false, event: "\(event)_load_all_failed", error: error.localizedDescription)
                completion(nil)
                return
            }

            let selection = selectCanonicalManager(from: managers ?? [])
            activeManager = selection.manager
            ensureAdminWebProxy(selection.manager)
            updateStatus(
                ok: true,
                event: event,
                manager: selection.manager,
                extra: [
                    "manager_count": managers?.count ?? 0,
                    "duplicate_count": selection.duplicates.count,
                    "needs_save": selection.needsSave,
                    "created": selection.created,
                ]
            )
            completion(selection.manager)
        }
    }

    private class func scheduleAdminTunnelReload(action: String) {
        queue.async {
            performAdminTunnelReload(action: action)
        }
    }

    private class func performAdminTunnelReload(action: String) {
        let configSync = syncConfigurationFileInternal()
        recordEvent("admin_control_action_requested", payload: [
            "action": action,
            "config_sync": configSync,
        ])
        reloadCanonicalManager(event: "admin_\(action)_manager_loaded") { manager in
            guard let manager else {
                return
            }
            configure(manager)
            manager.saveToPreferences { error in
                if let error {
                    updateStatus(
                        ok: false,
                        event: "admin_\(action)_save_failed",
                        manager: manager,
                        error: error.localizedDescription
                    )
                    return
                }
                reloadCanonicalManager(event: "admin_\(action)_preferences_reloaded") { reloadedManager in
                    guard let reloadedManager else {
                        return
                    }
                    waitForTunnelStopAndStart(reloadedManager, event: "admin_\(action)")
                }
            }
        }
    }

    private class func waitForTunnelStopAndStart(
        _ manager: NETunnelProviderManager,
        event: String,
        retriesRemaining: Int = 20
    ) {
        ensureAdminWebProxy(manager)
        let status = manager.connection.status
        switch status {
        case .invalid:
            updateStatus(ok: false, event: "\(event)_invalid", manager: manager)
        case .disconnected:
            start(manager)
        case .disconnecting:
            guard retriesRemaining > 0 else {
                updateStatus(ok: false, event: "\(event)_stop_timeout", manager: manager)
                return
            }
            queue.asyncAfter(deadline: .now() + 0.5) {
                reloadCanonicalManager(event: "\(event)_waiting_for_disconnect") { refreshedManager in
                    guard let refreshedManager else {
                        return
                    }
                    waitForTunnelStopAndStart(
                        refreshedManager,
                        event: event,
                        retriesRemaining: retriesRemaining - 1
                    )
                }
            }
        case .connected, .connecting, .reasserting:
            manager.connection.stopVPNTunnel()
            updateStatus(
                ok: true,
                event: "\(event)_stop_requested",
                manager: manager,
                extra: ["status_raw": status.rawValue]
            )
            queue.asyncAfter(deadline: .now() + 0.5) {
                reloadCanonicalManager(event: "\(event)_stop_recheck") { refreshedManager in
                    guard let refreshedManager else {
                        return
                    }
                    waitForTunnelStopAndStart(
                        refreshedManager,
                        event: event,
                        retriesRemaining: retriesRemaining - 1
                    )
                }
            }
        @unknown default:
            start(manager)
        }
    }

    private class func start(_ manager: NETunnelProviderManager) {
        ensureAdminWebProxy(manager)
        let status = manager.connection.status
        if status == .connected || status == .connecting || status == .reasserting {
            updateStatus(ok: true, event: "already_started", manager: manager, extra: ["started": true])
            return
        }

        do {
            try manager.connection.startVPNTunnel()
            updateStatus(ok: true, event: "start_succeeded", manager: manager, extra: ["started": true])
        } catch {
            updateStatus(ok: false, event: "start_failed", manager: manager, error: error.localizedDescription)
        }
    }

    private class func ensureAdminWebProxy(_ manager: NETunnelProviderManager?) {
        let runtimeConfig = loadRuntimeConfiguration()
        let bindHost = (runtimeConfig["admin_web_bind"] as? String) ?? webAdminBind
        let port = (runtimeConfig["admin_web_port"] as? Int) ?? webAdminPort
        let adminWebDirectory = resolveAdminWebDirectory()
        if adminWebProxy == nil {
            do {
                let proxy = try ObstacleBridgeIOSAppAdminWebProxy(
                    bindHost: bindHost,
                    port: port,
                    adminWebDirectory: adminWebDirectory,
                    statusProvider: {
                        UserDefaults.standard.dictionary(forKey: statusDefaultsKey) ?? [
                            "ok": true,
                            "status": "unknown",
                            "cached": false,
                        ]
                    }
                )
                adminWebProxy = proxy
                proxy.start()
                recordEvent("app_admin_web_proxy_started", payload: [
                    "bind_host": bindHost,
                    "port": port,
                    "admin_web_dir": adminWebDirectory.path,
                ])
            } catch {
                recordEvent("app_admin_web_proxy_failed", payload: [
                    "bind_host": bindHost,
                    "port": port,
                    "error": error.localizedDescription,
                ])
            }
        }
        adminWebProxy?.updateManager(manager)
        adminWebProxy?.updateAdminWebDirectory(adminWebDirectory)
    }

    private class func resolveAdminWebDirectory() -> URL {
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return URL(fileURLWithPath: ".")
        }
        let preferred = documents.appendingPathComponent("ObstacleBridge/admin_web", isDirectory: true)
        if FileManager.default.fileExists(atPath: preferred.path) {
            return preferred
        }
        return documents.appendingPathComponent("admin_web", isDirectory: true)
    }

    private class func requestProviderSnapshot(_ manager: NETunnelProviderManager, context: String) {
        guard manager.connection.status == .connected else {
            updateStatus(
                ok: true,
                event: "provider_snapshot_skipped",
                manager: manager,
                extra: [
                    "context": context,
                    "reason": "not_connected",
                ]
            )
            return
        }
        guard let session = manager.connection as? NETunnelProviderSession else {
            updateStatus(
                ok: false,
                event: "provider_snapshot_unavailable",
                manager: manager,
                error: "VPN connection is not a NETunnelProviderSession",
                extra: ["context": context]
            )
            return
        }
        let request: [String: Any] = [
            "command": "snapshot",
            "context": context,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: request) else {
            updateStatus(
                ok: false,
                event: "provider_snapshot_encode_failed",
                manager: manager,
                error: "failed to encode provider snapshot request",
                extra: ["context": context]
            )
            return
        }

        do {
            try session.sendProviderMessage(data) { responseData in
                guard let responseData else {
                    updateStatus(
                        ok: false,
                        event: "provider_snapshot_empty",
                        manager: manager,
                        error: "provider returned no snapshot data",
                        extra: ["context": context]
                    )
                    return
                }
                let response = (try? JSONSerialization.jsonObject(with: responseData)) as? [String: Any]
                updateStatus(
                    ok: true,
                    event: "provider_snapshot_received",
                    manager: manager,
                    extra: [
                        "context": context,
                        "provider_response": response ?? ["raw_bytes": responseData.count],
                    ]
                )
            }
        } catch {
            updateStatus(
                ok: false,
                event: "provider_snapshot_failed",
                manager: manager,
                error: error.localizedDescription,
                extra: ["context": context]
            )
        }
    }

    private class func requestProviderMessage(_ manager: NETunnelProviderManager, command: String, context: String) {
        guard let session = manager.connection as? NETunnelProviderSession else {
            updateStatus(
                ok: false,
                event: "provider_message_unavailable",
                manager: manager,
                error: "VPN connection is not a NETunnelProviderSession",
                extra: [
                    "command": command,
                    "context": context,
                ]
            )
            return
        }
        let request: [String: Any] = [
            "command": command,
            "context": context,
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: request) else {
            updateStatus(
                ok: false,
                event: "provider_message_encode_failed",
                manager: manager,
                error: "failed to encode provider message",
                extra: [
                    "command": command,
                    "context": context,
                ]
            )
            return
        }
        do {
            try session.sendProviderMessage(data) { responseData in
                guard let responseData else {
                    updateStatus(
                        ok: false,
                        event: "provider_message_empty",
                        manager: manager,
                        error: "provider returned no message data",
                        extra: [
                            "command": command,
                            "context": context,
                        ]
                    )
                    return
                }
                let response = (try? JSONSerialization.jsonObject(with: responseData)) as? [String: Any]
                updateStatus(
                    ok: true,
                    event: "provider_message_received",
                    manager: manager,
                    extra: [
                        "command": command,
                        "context": context,
                        "provider_response": response ?? ["raw_bytes": responseData.count],
                    ]
                )
            }
        } catch {
            updateStatus(
                ok: false,
                event: "provider_message_failed",
                manager: manager,
                error: error.localizedDescription,
                extra: [
                    "command": command,
                    "context": context,
                ]
            )
        }
    }

    private class func refreshStatusAsync() {
        queue.async {
            NETunnelProviderManager.loadAllFromPreferences { managers, error in
                if let error {
                    updateStatus(ok: false, event: "status_load_failed", error: error.localizedDescription)
                    return
                }
                let manager = (managers ?? []).first(where: isObstacleBridgeManager)
                updateStatus(ok: true, event: "status_refreshed", manager: manager ?? activeManager)
            }
        }
    }

    private class func updateStatus(
        ok: Bool,
        event: String,
        manager: NETunnelProviderManager? = nil,
        error: String? = nil,
        extra: [String: Any] = [:]
    ) {
        var payload: [String: Any] = [
            "ok": ok,
            "event": event,
            "provider_bundle_identifier": providerBundleIdentifier,
            "installed": manager != nil,
            "enabled": manager?.isEnabled ?? false,
            "status": statusText(manager?.connection.status),
            "status_raw": manager?.connection.status.rawValue ?? -1,
            "cached": true,
            "timestamp": ISO8601DateFormatter().string(from: Date()),
        ]
        if let error {
            payload["error"] = error
        }
        if let manager {
            payload["localized_description"] = manager.localizedDescription ?? ""
            if let protocolConfiguration = manager.protocolConfiguration as? NETunnelProviderProtocol {
                payload["protocol_server_address"] = protocolConfiguration.serverAddress ?? ""
                payload["protocol_username"] = protocolConfiguration.username ?? ""
                payload["protocol_provider_bundle_identifier"] = protocolConfiguration.providerBundleIdentifier ?? ""
                payload["provider_configuration_version"] =
                    protocolConfiguration.providerConfiguration?["configuration_version"] as? String ?? ""
            }
        }
        for (key, value) in extra {
            payload[key] = value
        }
        UserDefaults.standard.set(payload, forKey: statusDefaultsKey)
        recordEvent(event, payload: payload)
    }

    private class func recordEvent(_ event: String, payload: [String: Any] = [:]) {
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return
        }
        let logDirectory = documents.appendingPathComponent("logs", isDirectory: true)
        try? FileManager.default.createDirectory(at: logDirectory, withIntermediateDirectories: true)
        let logURL = logDirectory.appendingPathComponent("ios-native-tunnel-control.jsonl")
        var line = payload
        line["native_event"] = event
        line["timestamp"] = ISO8601DateFormatter().string(from: Date())
        guard JSONSerialization.isValidJSONObject(line),
              let data = try? JSONSerialization.data(withJSONObject: line, options: [.sortedKeys]),
              let text = String(data: data, encoding: .utf8)
        else {
            return
        }
        if let handle = try? FileHandle(forWritingTo: logURL) {
            defer {
                try? handle.close()
            }
            handle.seekToEndOfFile()
            handle.write(Data((text + "\n").utf8))
            return
        }
        try? (text + "\n").write(to: logURL, atomically: true, encoding: .utf8)
    }

    private class func loadRuntimeConfiguration() -> [String: Any] {
        let defaults: [String: Any] = [
            "admin_web": true,
            "admin_web_bind": webAdminBind,
            "admin_web_port": webAdminPort,
            "admin_web_path": "/",
            "log": "DEBUG",
            "file_level": "DEBUG",
            "console_level": "INFO",
        ]
        guard let documents = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            return defaults
        }
        let configURL = documents.appendingPathComponent("config/ObstacleBridge.cfg")
        guard let data = try? Data(contentsOf: configURL),
              let object = try? JSONSerialization.jsonObject(with: data),
              let payload = object as? [String: Any]
        else {
            return defaults
        }
        var flattened = defaults
        for (key, value) in payload {
            if let section = value as? [String: Any] {
                for (sectionKey, sectionValue) in section {
                    flattened[sectionKey] = sectionValue
                }
            } else {
                flattened[key] = value
            }
        }
        return flattened
    }

    private class func ipserverRuntimeConfiguration() -> [String: Any] {
        var config = loadRuntimeConfiguration()
        config["admin_web"] = true
        config["admin_web_bind"] = webAdminBind
        config["admin_web_port"] = webAdminPort
        config["admin_web_path"] = "/"
        return config
    }

    private class func statusText(_ status: NEVPNStatus?) -> String {
        guard let status else {
            return "unknown"
        }
        switch status {
        case .invalid:
            return "invalid"
        case .disconnected:
            return "disconnected"
        case .connecting:
            return "connecting"
        case .connected:
            return "connected"
        case .reasserting:
            return "reasserting"
        case .disconnecting:
            return "disconnecting"
        @unknown default:
            return "unknown"
        }
    }


private final class ObstacleBridgeIOSAppAdminWebProxy {
    private let statusProvider: () -> [String: Any]
    private let stateQueue = DispatchQueue(label: "com.obstaclebridge.ios-admin-web-proxy")
    private let bindHost: String
    private let port: Int
    private var manager: NETunnelProviderManager?
    private var adminWebDirectory: URL
    private var server: ObstacleBridgeWebAdminServer!

    init(
        bindHost: String,
        port: Int,
        adminWebDirectory: URL,
        statusProvider: @escaping () -> [String: Any]
    ) throws {
        self.bindHost = bindHost
        self.port = port
        self.adminWebDirectory = adminWebDirectory
        self.statusProvider = statusProvider
        self.server = try ObstacleBridgeWebAdminServer(
            bindHost: bindHost,
            port: port,
            fallbackIndexTitle: "ObstacleBridge iOS App Proxy",
            fallbackIndexSubtitle: "App-side web admin proxy backed by the packet-tunnel shared admin API.",
            statusProvider: { [weak self] in
                self?.statusSnapshot() ?? ["ok": false, "error": "proxy unavailable"]
            },
            apiProvider: { [weak self] method, path, headers, body in
                self?.apiResponse(method: method, path: path, headers: headers, body: body)
            },
            staticFileProvider: { [weak self] path in
                self?.staticFileResponse(path: path)
            },
            liveTopicProvider: { [weak self] topic in
                self?.liveTopicPayload(topic: topic)
            }
        )
    }

    func start() {
        server.start()
    }

    func updateManager(_ manager: NETunnelProviderManager?) {
        stateQueue.sync {
            self.manager = manager
        }
    }

    func updateAdminWebDirectory(_ adminWebDirectory: URL) {
        stateQueue.sync {
            self.adminWebDirectory = adminWebDirectory
        }
    }

    private func statusSnapshot() -> [String: Any] {
        if let payload = providerJSONBody(method: "GET", path: "/api/status") as? [String: Any] {
            return payload
        }
        return statusProvider()
    }

    private func apiResponse(method: String, path: String, headers: [String: String], body: Data?) -> ObstacleBridgeAdminAPIResponse? {
        guard let envelope = providerAdminAPIEnvelope(method: method, path: path, headers: headers, body: body) else {
            return ObstacleBridgeAdminAPI.jsonResponse([
                "ok": false,
                "error": "provider unavailable",
                "path": path,
            ], statusLine: "HTTP/1.1 503 Service Unavailable")
        }
        let response = adjustedAdminAPIEnvelope(envelope, method: method, path: path, body: body)
        let rendered = providerAdminAPIResponse(from: response)
        return ObstacleBridgeAdminAPIResponse(
            statusLine: rendered.statusLine,
            contentType: rendered.contentType,
            body: rendered.body,
            headers: []
        )
    }

    private func liveTopicPayload(topic: String) -> Any? {
        switch topic {
        case "status":
            return providerJSONBody(method: "GET", path: "/api/status")
        case "connections":
            return providerJSONBody(method: "GET", path: "/api/connections")
        case "peers":
            return providerJSONBody(method: "GET", path: "/api/peers")
        case "meta":
            return providerJSONBody(method: "GET", path: "/api/meta")
        default:
            return nil
        }
    }

    private func providerJSONBody(method: String, path: String) -> Any? {
        let response = providerMessage([
            "command": "admin_api_request",
            "method": method,
            "path": path,
        ])
        return response?["body_json"]
    }

    private func providerAdminAPIEnvelope(
        method: String,
        path: String,
        headers: [String: String],
        body: Data?
    ) -> [String: Any]? {
        var payload: [String: Any] = [
            "command": "admin_api_request",
            "method": method,
            "path": path,
            "headers": headers,
        ]
        if let body, !body.isEmpty {
            payload["body_base64"] = body.base64EncodedString()
        }
        return providerMessage(payload)
    }

    private func providerAdminAPIResponse(
        from response: [String: Any]
    ) -> (statusLine: String, contentType: String, body: Data) {
        let statusLine = response["status_line"] as? String ?? "HTTP/1.1 200 OK"
        let contentType = response["content_type"] as? String ?? "application/json; charset=utf-8"
        if let bodyJSON = response["body_json"] {
            return (statusLine, contentType, ObstacleBridgeAdminAPI.jsonBody(bodyJSON))
        }
        if let bodyUTF8 = response["body_utf8"] as? String {
            return (statusLine, contentType, Data(bodyUTF8.utf8))
        }
        if let bodyBase64 = response["body_base64"] as? String,
           let bodyData = Data(base64Encoded: bodyBase64) {
            return (statusLine, contentType, bodyData)
        }
        return (statusLine, contentType, Data())
    }

    private func providerAdminAPIResponse(
        method: String,
        path: String,
        headers: [String: String],
        body: Data?
    ) -> (statusLine: String, contentType: String, body: Data)? {
        guard let response = providerAdminAPIEnvelope(method: method, path: path, headers: headers, body: body) else {
            return nil
        }
        return providerAdminAPIResponse(from: response)
    }

    private func adjustedAdminAPIEnvelope(
        _ response: [String: Any],
        method: String,
        path: String,
        body: Data?
    ) -> [String: Any] {
        guard method.uppercased() == "POST",
              isSuccessfulStatusLine(response["status_line"] as? String ?? "HTTP/1.1 200 OK"),
              var bodyJSON = response["body_json"] as? [String: Any],
              (bodyJSON["ok"] as? Bool) != false else {
            return response
        }

        switch path {
        case "/api/restart":
            ObstacleBridgeTunnelControl.scheduleAdminTunnelReload(action: "restart")
            bodyJSON["restart_requested"] = true
            bodyJSON["restart_supported"] = true
            bodyJSON["restart_delay_sec"] = 0
            bodyJSON["restart_embedded"] = false
        case "/api/reconnect":
            ObstacleBridgeTunnelControl.scheduleAdminTunnelReload(action: "reconnect")
            bodyJSON["reconnect_requested"] = true
            bodyJSON["reconnect_supported"] = true
        case "/api/config" where configSaveRequestsRestart(body: body):
            ObstacleBridgeTunnelControl.scheduleAdminTunnelReload(action: "restart_after_save")
            bodyJSON["restart_requested"] = true
            bodyJSON["restart_supported"] = true
            bodyJSON["restart_delay_sec"] = 0
            bodyJSON["restart_embedded"] = false
        default:
            return response
        }

        var adjusted = response
        adjusted["body_json"] = bodyJSON
        return adjusted
    }

    private func isSuccessfulStatusLine(_ statusLine: String) -> Bool {
        let parts = statusLine.split(separator: " ")
        guard parts.count >= 2, let code = Int(parts[1]) else {
            return false
        }
        return (200 ..< 300).contains(code)
    }

    private func configSaveRequestsRestart(body: Data?) -> Bool {
        guard let body,
              let object = try? JSONSerialization.jsonObject(with: body),
              let payload = object as? [String: Any] else {
            return false
        }
        return (payload["restart_after_save"] as? Bool) ?? false
    }

    private func providerMessage(_ payload: [String: Any]) -> [String: Any]? {
        guard let session = stateQueue.sync(execute: { manager?.connection as? NETunnelProviderSession }) else {
            return nil
        }
        guard let data = try? JSONSerialization.data(withJSONObject: payload) else {
            return nil
        }

        let semaphore = DispatchSemaphore(value: 0)
        var response: [String: Any]?
        do {
            try session.sendProviderMessage(data) { responseData in
                defer { semaphore.signal() }
                guard let responseData,
                      let decoded = try? JSONSerialization.jsonObject(with: responseData) as? [String: Any] else {
                    return
                }
                response = decoded
            }
        } catch {
            return nil
        }
        _ = semaphore.wait(timeout: .now() + 2.0)
        return response
    }

    private func staticFileResponse(path: String) -> (contentType: String, body: Data)? {
        let cleanedPath = normalizeStaticPath(path)
        let adminWebDirectory = stateQueue.sync(execute: { self.adminWebDirectory })
        let fileURL = adminWebDirectory.appendingPathComponent(cleanedPath, isDirectory: false)
        guard fileURL.path.hasPrefix(adminWebDirectory.path),
              let data = try? Data(contentsOf: fileURL) else {
            return nil
        }
        return (contentType(for: fileURL.pathExtension), data)
    }

    private func normalizeStaticPath(_ rawPath: String) -> String {
        let basePath = rawPath.split(separator: "?", maxSplits: 1).first.map(String.init) ?? "/"
        let candidate = basePath == "/" ? "index.html" : String(basePath.drop(while: { $0 == "/" }))
        let components = candidate.split(separator: "/").filter { $0 != "." && $0 != ".." }
        return components.isEmpty ? "index.html" : components.joined(separator: "/")
    }

    private func contentType(for pathExtension: String) -> String {
        switch pathExtension.lowercased() {
        case "html":
            return "text/html; charset=utf-8"
        case "js":
            return "application/javascript; charset=utf-8"
        case "css":
            return "text/css; charset=utf-8"
        case "json":
            return "application/json; charset=utf-8"
        case "svg":
            return "image/svg+xml"
        default:
            return "application/octet-stream"
        }
    }
}
    private class func jsonString(_ payload: [String: Any]) -> String {
        guard JSONSerialization.isValidJSONObject(payload),
              let data = try? JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys]),
              let text = String(data: data, encoding: .utf8)
        else {
            return "{\"ok\":false,\"error\":\"failed to encode tunnel-control response\"}"
        }
        return text
    }
}
